In [1]:
import numpy as np

In [2]:
vector=np.array([2,4,6])
print(vector)

[2 4 6]


In [3]:
import numpy as np
matrix=np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


In [ ]:
# addition# 
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[4,5],[6,7]])
print(matrix1 + matrix2)

[[ 5  7]
 [ 9 11]]


In [5]:
# mul
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[4, 5], [6, 7]])
print(matrix1 * matrix2)

[[ 4 10]
 [18 28]]


In [6]:
# dot
# addition#
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[4, 5], [6, 7]])
print(np.dot(matrix1,matrix2))

[[16 19]
 [36 43]]
